FROM debian:latest
FROM python:3

RUN apt-get update
RUN apt-get install -y supervisor redis
RUN pip3 install rq Flask more_itertools Flask_SQLAlchemy redis Werkzeug

COPY repo/ /repo/
COPY supervisor.conf /etc/supervisord.conf

CMD ['/usr/bin/supervisord']